name: Update EPG

on:
  schedule:
    - cron: "0 */6 * * *"   # her 6 saatte bir çalışacak
  workflow_dispatch:        # elle de tetikleyebilirsin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python generate_epg.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add turkey.xml
          git commit -m "Update EPG" || echo "No changes"
          git push
